[theme]
primaryColor = "#000000" #cor dos botoes,slides e elementos
backgroundColor = "#ffffff" #cor de fundo do corpo principal
secondaryBackgroundColor = "#396bff" #cor de fundo da barra
textColor = "#000000"
font = "sans serif"
